import sanitizeHtml from "sanitize-html";

export function sanitizeMailHtml(value?: string): string | undefined {
  if (!value) return undefined;
  return sanitizeHtml(value, {
    allowedTags: [
      ...sanitizeHtml.defaults.allowedTags,
      "img",
      "style",
      "span",
      "center",
      "font",
      "table",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "th",
      "td",
      "section",
      "header",
      "footer",
      "main",
      "article",
      "aside",
      "figure",
      "figcaption",
      "svg",
      "path",
      "u",
      "s",
      "strike",
      "sub",
      "sup",
      "hr",
      "br",
    ],
    allowedAttributes: {
      "*": [
        "class",
        "style",
        "title",
        "id",
        "dir",
        "lang",
        "align",
        "valign",
        "bgcolor",
        "color",
        "width",
        "height",
      ],
      a: ["href", "name", "target", "rel"],
      img: ["alt", "height", "width", "src", "style", "border"],
      table: [
        "border",
        "cellpadding",
        "cellspacing",
        "width",
        "height",
        "align",
        "bgcolor",
        "style",
      ],
      td: [
        "colspan",
        "rowspan",
        "width",
        "height",
        "align",
        "valign",
        "bgcolor",
        "style",
      ],
      th: [
        "colspan",
        "rowspan",
        "width",
        "height",
        "align",
        "valign",
        "bgcolor",
        "style",
      ],
      font: ["color", "face", "size"],
    },
    allowedSchemes: ["https", "http", "mailto", "cid", "data"],
    allowProtocolRelative: false,
    disallowedTagsMode: "discard",
    transformTags: {
      a: sanitizeHtml.simpleTransform("a", { rel: "noopener noreferrer" }),
    },
  });
}

export function sanitizeOutboundMailHtml(value?: string): string | undefined {
  if (!value) return undefined;
  return sanitizeHtml(value, {
    allowedTags: [
      ...sanitizeHtml.defaults.allowedTags,
      "img",
      "style",
      "span",
      "center",
      "font",
      "table",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "th",
      "td",
      "section",
      "header",
      "footer",
      "u",
      "s",
      "sub",
      "sup",
      "hr",
      "br",
    ],
    allowedAttributes: {
      "*": [
        "class",
        "style",
        "title",
        "id",
        "dir",
        "align",
        "valign",
        "bgcolor",
        "color",
        "width",
        "height",
      ],
      a: ["href", "name", "target", "rel"],
      img: ["alt", "height", "width", "src", "style", "border"],
      table: [
        "border",
        "cellpadding",
        "cellspacing",
        "width",
        "height",
        "align",
        "bgcolor",
        "style",
      ],
      td: ["colspan", "rowspan", "width", "height", "align", "valign", "bgcolor", "style"],
      th: ["colspan", "rowspan", "width", "height", "align", "valign", "bgcolor", "style"],
      font: ["color", "face", "size"],
    },
    allowedSchemes: ["https", "http", "mailto", "cid", "data"],
    allowProtocolRelative: false,
    disallowedTagsMode: "discard",
    transformTags: {
      a: sanitizeHtml.simpleTransform("a", { rel: "noopener noreferrer" }),
    },
  });
}
