import type { DashboardProject } from "@/features/dashboard/types/project.types";

export const USE_MOCK_DATA = true;

export const MOCK_PROJECTS: DashboardProject[] = [
  {
    slug: "kontinue-ai",
    name: "Kontinue AI",
    domain: "kontinue-ai.multivrs.dev",
    repo: "colesites/kontinue-ai",
    status: "ready",
    commitMessage: "feat: implement comprehensive resource access...",
    branch: "main",
    updatedAt: "2m ago",
    analytics: {
      pageVisits: "12.4k",
      speedInsightScore: 98,
    }
  },
  {
    slug: "web-portal",
    name: "Web Portal",
    domain: "web-portal.multivrs.dev",
    repo: "colesites/web-portal",
    status: "building",
    commitMessage: "feat: redesign dashboard layout",
    branch: "feat/new-dashboard",
    updatedAt: "5m ago",
    analytics: {
      pageVisits: "8.1k",
      speedInsightScore: 85,
    }
  },
  {
    slug: "api-service",
    name: "API Service",
    domain: "api-service.multivrs.dev",
    repo: "colesites/api-service",
    status: "error",
    commitMessage: "fix: resolve auth token generation bug",
    branch: "fix/auth-bug",
    updatedAt: "2h ago",
    analytics: {
      pageVisits: "45.2k",
      speedInsightScore: 92,
    }
  },
];

export const MOCK_DEPLOYMENTS = [
  {
    id: "dep_1a2b3c4d5e",
    project: "kontinue-ai",
    status: "Ready",
    branch: "main",
    duration: "1m 6s",
    url: "https://kontinue-ai.multivrs.dev",
    createdAt: new Date().toISOString(),
    commitMessage: "feat: ensure consistent ID comparison as strings in hooks",
    environment: "Production",
    commitSha: "155489a",
  },
  {
    id: "dep_9f8e7d6c5b",
    project: "web-portal",
    status: "Building",
    branch: "feat/new-dashboard",
    duration: "1m 2s",
    url: "https://web-portal-feat-new.multivrs.dev",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    commitMessage: "feat: improve library item reference handling in useServices",
    environment: "Preview",
    commitSha: "53db537",
  },
  {
    id: "dep_5x4y3z2w1v",
    project: "api-service",
    status: "Failed",
    branch: "fix/auth-bug",
    duration: "57s",
    url: "https://api-service-fix-auth.multivrs.dev",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    commitMessage: "fix: ensure consistent app URL format across window creation functions",
    environment: "Preview",
    commitSha: "ad74f74",
  },
  {
    id: "dep_2p3q4r5s6t",
    project: "marketing-site",
    status: "Ready",
    branch: "main",
    duration: "45s",
    url: "https://marketing-site.multivrs.dev",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    commitMessage: "chore: update dependencies and versions, refine UI kit starter template",
    environment: "Production",
    commitSha: "5967293",
  },
  {
    id: "dep_8k9l0m1n2o",
    project: "kontinue-ai",
    status: "Ready",
    branch: "main",
    duration: "1m 11s",
    url: "https://kontinue-ai.multivrs.dev",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    commitMessage: "feat: enhance NDI input handling with client ID support",
    environment: "Production",
    commitSha: "1c7977e",
  },
  {
    id: "dep_3p4q5r6s7t",
    project: "web-portal",
    status: "Ready",
    branch: "feat/sidebar-nav",
    duration: "1m 22s",
    url: "https://web-portal-feat-sidebar.multivrs.dev",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    commitMessage: "feat: enhance sidebar and panel components with improved overflow handling",
    environment: "Preview",
    commitSha: "f6cd312",
  },
  {
    id: "dep_7u8v9w0x1y",
    project: "api-service",
    status: "Ready",
    branch: "main",
    duration: "1m 3s",
    url: "https://api-service.multivrs.dev",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    commitMessage: "feat: implement media and worship stage window management with live state",
    environment: "Production",
    commitSha: "8d8b186",
  }
];
