import { capabilities } from "./types";

export const COMPUTE_CAPABILITIES = capabilities([
  {
    id: "function-cpu",
    name: "Active CPU (Multivrs Functions)",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Container function execution duration is metered at the serving edge",
  },
  {
    id: "function-memory",
    name: "Provisioned Memory (Multivrs Functions)",
    status: "preview",
    provider: "cloudflare",
    metered: true,
    evidence: "Container instance sizing exists; configured-memory sampling remains preview",
  },
  {
    id: "function-invocations",
    name: "Invocations (Multivrs Functions)",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Function router and per-project invocation meter",
  },
  {
    id: "services",
    name: "Multivrs Services",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Worker service bindings and per-deployment runtimes",
  },
  {
    id: "sandbox-cpu",
    name: "Active CPU (Multivrs Sandbox)",
    status: "preview",
    provider: "cloudflare",
    metered: true,
    evidence: "Sandbox command duration is persisted in the usage ledger",
  },
  {
    id: "sandbox-memory",
    name: "Provisioned Memory (Multivrs Sandbox)",
    status: "preview",
    provider: "cloudflare",
    metered: true,
    evidence: "Sandbox provisioned duration is persisted in the usage ledger",
  },
  {
    id: "sandbox-creation",
    name: "Creation (Multivrs Sandbox)",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Authenticated create and destroy APIs",
  },
  {
    id: "sandbox-network",
    name: "Network (Multivrs Sandbox)",
    status: "preview",
    provider: "cloudflare",
    metered: true,
    evidence: "Build checkout network exists; user sandbox egress policy remains",
  },
  {
    id: "concurrent-sandboxes",
    name: "Concurrent Sandboxes",
    status: "available",
    provider: "multivrs",
    metered: true,
    evidence: "Persisted sandbox lifecycle with enforced project concurrency quota",
  },
  {
    id: "snapshot-storage",
    name: "Snapshot Storage (Multivrs Sandbox)",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Snapshot persistence is not provisioned",
  },
  {
    id: "origin-transfer",
    name: "Fast Origin Transfer",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Compute response streams are byte-metered at the serving edge",
  },
  {
    id: "workflow-events",
    name: "Events (Multivrs Workflows)",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Cloudflare Workflows binding, durable runner, manual triggers, and cron dispatcher",
  },
  {
    id: "workflow-written",
    name: "Data Written (Multivrs Workflows)",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Workflow payload and output byte meters",
  },
  {
    id: "workflow-retained",
    name: "Data Retained (Multivrs Workflows)",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Persisted workflow-run input/output storage meter",
  },
  {
    id: "api-operations",
    name: "API Operations",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Typed project APIs and API tokens",
  },
  {
    id: "cron-jobs",
    name: "Cron Jobs (Multivrs Compute)",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "UTC five-field cron parser with idempotent database claims and minute dispatcher",
  },
] as const);
