import { capabilities } from "./types";

export const CONTENT_CAPABILITIES = capabilities([
  {
    id: "cdn-cache",
    name: "Zero-config CDN Cache",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Cache API and immutable R2 artifacts",
  },
  {
    id: "compression",
    name: "Automated Compression",
    status: "available",
    provider: "cloudflare",
    metered: false,
    evidence: "Cloudflare Brotli and gzip delivery",
  },
  {
    id: "background-revalidation",
    name: "Background Revalidation",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Queue-backed regeneration consumer",
  },
  {
    id: "swr",
    name: "Stale-While-Revalidate",
    status: "available",
    provider: "multivrs",
    metered: true,
    evidence: "Incremental cache stale window and queue",
  },
  {
    id: "isr-reads",
    name: "ISR Reads",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "R2 incremental cache reads",
  },
  {
    id: "isr-writes",
    name: "ISR Writes",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "R2 writes with Durable Object locks",
  },
  {
    id: "storage-size",
    name: "Storage Size",
    status: "available",
    provider: "cloudflare",
    metered: true,
    evidence: "R2 object size aggregation",
  },
  {
    id: "simple-operations",
    name: "Simple Operations",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "R2 operation metering",
  },
  {
    id: "advanced-operations",
    name: "Advanced Operations",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Signed upload and mutation metering",
  },
  {
    id: "blob-transfer",
    name: "Blob Data Transfer",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "R2 streamed delivery telemetry",
  },
  {
    id: "image-transformations",
    name: "Image Transformations",
    status: "available",
    provider: "cloudflare",
    metered: true,
    evidence: "Cloudflare Images binding",
  },
  {
    id: "image-cache-reads",
    name: "Image Cache Reads",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Cache API hit metering",
  },
  {
    id: "image-cache-writes",
    name: "Image Cache Writes",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Cache API write metering",
  },
  {
    id: "edge-config-reads",
    name: "Edge Config Reads",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Versioned KV runtime reads",
  },
  {
    id: "edge-config-writes",
    name: "Edge Config Writes",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Neon source with KV publish",
  },
  {
    id: "microfrontends",
    name: "Microfrontends",
    status: "available",
    provider: "multivrs",
    metered: true,
    evidence: "Path mount model and runtime config",
  },
  {
    id: "microfrontend-routing",
    name: "Microfrontend Routing",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Cross-project serving dispatch",
  },
] as const);
