import { capabilities } from "./types";

export const DELIVERY_CAPABILITIES = capabilities([
  {
    id: "global-pops",
    name: "Global Points of Presence",
    status: "available",
    provider: "cloudflare",
    metered: false,
    evidence: "Cloudflare Workers and cache edge",
  },
  {
    id: "regions",
    name: "Multivrs Regions",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Global edge with compute placement managed by Cloudflare",
  },
  {
    id: "automatic-routing",
    name: "Automatic Routing",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Serve Worker hostname and manifest router",
  },
  {
    id: "https-certificates",
    name: "HTTPS Certificates",
    status: "available",
    provider: "cloudflare",
    metered: false,
    evidence: "Cloudflare custom hostnames certificate issuance",
  },
  {
    id: "tls",
    name: "TLS/SSL Encryption",
    status: "available",
    provider: "cloudflare",
    metered: false,
    evidence: "Cloudflare edge TLS",
  },
  {
    id: "load-balancing",
    name: "Traffic Load Balancing",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Requires Cloudflare Load Balancing provisioning",
  },
  {
    id: "private-region-network",
    name: "Private Inter-Region Network",
    status: "infrastructure-required",
    provider: "external",
    metered: true,
    evidence: "Requires dedicated private regional infrastructure",
  },
  {
    id: "region-failover",
    name: "Automatic Region Failover",
    status: "preview",
    provider: "cloudflare",
    metered: false,
    evidence: "Edge failover is global; compute failover policy remains to be provisioned",
  },
  {
    id: "reverse-proxy",
    name: "Reverse Proxy",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Serve Worker proxy and compute service bindings",
  },
  {
    id: "rewrites",
    name: "Rewrites",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Routing manifest matcher",
  },
  {
    id: "redirects",
    name: "Redirects",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Manifest and bulk redirect runtime",
  },
  {
    id: "middleware",
    name: "Middleware Support",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Edge dispatch and framework route output",
  },
  {
    id: "edge-requests",
    name: "Edge Requests",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Serve Worker Analytics Engine request events",
  },
  {
    id: "fast-data-transfer",
    name: "Fast Data Transfer",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Response-byte telemetry and Cloudflare delivery",
  },
] as const);
