import { capabilities } from "./types";

export const DEPLOYMENT_CAPABILITIES = capabilities([
  {
    id: "automatic-cicd",
    name: "Automatic CI/CD",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Signed GitHub push and pull-request webhooks dispatch the build queue",
  },
  {
    id: "environment-variables",
    name: "Environment Variables",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Encrypted environment-scoped values",
  },
  {
    id: "build-logs",
    name: "Build Logs",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Streamed sandbox logs persisted per deployment",
  },
  {
    id: "remote-cache",
    name: "Remote Cache",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "R2-backed build cache restore and publish pipeline",
  },
  {
    id: "monorepo",
    name: "Monorepo Support",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Root directory and build settings",
  },
  {
    id: "webhook-triggers",
    name: "Webhook Triggers",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "HMAC-verified idempotent GitHub deployment webhooks",
  },
  {
    id: "custom-environments",
    name: "Custom Environments",
    status: "preview",
    provider: "multivrs",
    metered: false,
    evidence: "Production and preview exist; named environments remain",
  },
  {
    id: "standard-build-minutes",
    name: "Standard Machines (Build Minutes)",
    status: "available",
    provider: "cloudflare",
    metered: true,
    evidence: "Sandbox build duration ledger",
  },
  {
    id: "enhanced-build-minutes",
    name: "Enhanced Machines (Build Minutes)",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Machine class is not provisioned",
  },
  {
    id: "turbo-build-minutes",
    name: "Turbo Machines (Build Minutes)",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Machine class is not provisioned",
  },
  {
    id: "elastic-build-minutes",
    name: "Elastic Machines (Build Minutes)",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Elastic builder pool is not provisioned",
  },
  {
    id: "unlimited-deployments",
    name: "Unlimited Deployments",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "No deployment-count hard limit",
  },
  {
    id: "instant-rollback",
    name: "Instant Rollback",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Immutable artifact pointer promotion",
  },
  {
    id: "multi-tenant",
    name: "Multi-tenant Support",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Hostname isolation exists; Workers for Platforms dispatch remains",
  },
  {
    id: "skew-protection",
    name: "Skew Protection",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: false,
    evidence: "Client deployment affinity remains",
  },
  {
    id: "rolling-releases",
    name: "Rolling Releases",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: false,
    evidence: "Weighted deployment routing remains",
  },
  {
    id: "preview-suffix",
    name: "Preview Deployment Suffix",
    status: "infrastructure-required",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Custom preview hostname suffix remains",
  },
] as const);
