import { capabilities } from "./types";

export const EXPERIENCE_CAPABILITIES = capabilities([
  {
    id: "developer-seat",
    name: "Developer Seat",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "Workspace membership and billing remain",
  },
  {
    id: "viewer-seat",
    name: "Viewer Seat",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "Workspace membership and RBAC remain",
  },
  {
    id: "billing-seat",
    name: "Billing Seat",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "Workspace billing role remains",
  },
  {
    id: "comments",
    name: "Comments",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: false,
    evidence: "Preview annotation service remains",
  },
  {
    id: "layout-shift-tool",
    name: "Layout Shift Tool",
    status: "preview",
    provider: "multivrs",
    metered: false,
    evidence: "CLS collection exists; visual overlay remains",
  },
  {
    id: "draft-mode",
    name: "Draft Mode",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Framework preview deployments and Next draft mode",
  },
  {
    id: "productivity-integrations",
    name: "Productivity Integrations",
    status: "preview",
    provider: "multivrs",
    metered: false,
    evidence: "OIDC integration foundation",
  },
  {
    id: "previewers",
    name: "Previewers",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: false,
    evidence: "Preview access membership remains",
  },
  {
    id: "accessibility-audit",
    name: "Accessibility Audit",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "Automated audit runner remains",
  },
  {
    id: "flags-explorer",
    name: "Flags Explorer",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: false,
    evidence: "Flag registry and toolbar remain",
  },
  {
    id: "multivrs-flags",
    name: "Multivrs Flags",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "Edge flag store remains",
  },
  {
    id: "usage-dashboard",
    name: "Usage Dashboard",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "Analytics Engine and Neon usage aggregation",
  },
  {
    id: "observability",
    name: "Observability",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Live request, transfer, latency, and error telemetry",
  },
  {
    id: "observability-plus",
    name: "Observability Plus",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Query, retention, metrics, and alert storage remain",
  },
  {
    id: "speed-insights",
    name: "Speed Insights",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "First-party RUM Web Vitals pipeline",
  },
  {
    id: "web-analytics",
    name: "Web Analytics",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "First-party pageview, visitor, session, route, and referrer events",
  },
  {
    id: "web-analytics-plus",
    name: "Web Analytics Plus",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "30-day windows and UTM reporting",
  },
  {
    id: "runtime-logs",
    name: "Runtime Logs",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Container stdout/stderr ingestion with persisted source and bounded batches",
  },
  {
    id: "session-tracing",
    name: "Session Tracing",
    status: "preview",
    provider: "multivrs",
    metered: true,
    evidence:
      "First-party session affinity now correlates browser and request telemetry; span UI remains",
  },
  {
    id: "log-drains",
    name: "Log Drains",
    status: "preview",
    provider: "multivrs",
    metered: true,
    evidence:
      "Encrypted drain secrets and signed HTTPS delivery exist; durable delivery retries remain",
  },
] as const);
