import { capabilities } from "./types";

export const FIREWALL_CAPABILITIES = capabilities([
  {
    id: "custom-firewall-rules",
    name: "Custom Firewall Rules",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Typed rule engine and project rule persistence",
  },
  {
    id: "ip-blocking",
    name: "IP Blocking",
    status: "available",
    provider: "multivrs+cloudflare",
    metered: false,
    evidence: "IP conditions evaluated with Cloudflare client IP",
  },
  {
    id: "system-bypass-rules",
    name: "System Bypass Rules",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Audited, expiring, project- and path-scoped HMAC bypass tokens",
  },
  {
    id: "rate-limiting",
    name: "Rate Limiting",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Cloudflare Rate Limit binding with project rules",
  },
  {
    id: "owasp",
    name: "OWASP Core Ruleset (managed)",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Requires Cloudflare for SaaS managed WAF entitlement",
  },
  {
    id: "ddos",
    name: "Automated DDoS Mitigation",
    status: "available",
    provider: "cloudflare",
    metered: false,
    evidence: "Cloudflare network-layer DDoS protection",
  },
  {
    id: "ai-bots",
    name: "AI Bots (managed ruleset)",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Requires Cloudflare managed ruleset entitlement",
  },
  {
    id: "bot-protection",
    name: "Bot Protection (managed ruleset)",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Custom bot policy is available; managed entitlement is optional",
  },
  {
    id: "bot-id",
    name: "BotID",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Requires Cloudflare Bot Management signals",
  },
  {
    id: "challenge-mode",
    name: "Attack Challenge Mode",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Attack mode exists; interactive Turnstile challenge is being added",
  },
] as const);
