import { COMPUTE_CAPABILITIES } from "./compute";
import { CONTENT_CAPABILITIES } from "./content";
import { DELIVERY_CAPABILITIES } from "./delivery";
import { DEPLOYMENT_CAPABILITIES } from "./deployments";
import { EXPERIENCE_CAPABILITIES } from "./experience";
import { FIREWALL_CAPABILITIES } from "./firewall";
import { SECURITY_CAPABILITIES } from "./security";

export * from "./types";
export {
  COMPUTE_CAPABILITIES,
  CONTENT_CAPABILITIES,
  DELIVERY_CAPABILITIES,
  DEPLOYMENT_CAPABILITIES,
  EXPERIENCE_CAPABILITIES,
  FIREWALL_CAPABILITIES,
  SECURITY_CAPABILITIES,
};

export const PLATFORM_CAPABILITIES = [
  ...DELIVERY_CAPABILITIES,
  ...FIREWALL_CAPABILITIES,
  ...CONTENT_CAPABILITIES,
  ...COMPUTE_CAPABILITIES,
  ...DEPLOYMENT_CAPABILITIES,
  ...EXPERIENCE_CAPABILITIES,
  ...SECURITY_CAPABILITIES,
] as const;
