import { capabilities } from "./types";

export const SECURITY_CAPABILITIES = capabilities([
  {
    id: "mfa",
    name: "Multi-Factor Authentication (MFA)",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Better Auth TOTP, recovery codes, trusted-device verification, and account UI",
  },
  {
    id: "rbac",
    name: "Role-Based Access Control",
    status: "preview",
    provider: "multivrs",
    metered: false,
    evidence:
      "Organization membership and owner/admin/developer/viewer/billing roles exist; project-wide DAL enforcement is being expanded",
  },
  {
    id: "audit-logs",
    name: "Audit Logs",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "User action audit event ledger",
  },
  {
    id: "saml",
    name: "SAML Single Sign-On (SSO)",
    status: "infrastructure-required",
    provider: "external",
    metered: true,
    evidence: "Enterprise identity provider integration remains",
  },
  {
    id: "scim",
    name: "Directory Sync (SCIM)",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "SCIM server and directory model remain",
  },
  {
    id: "deployment-protection",
    name: "Advanced Deployment Protection",
    status: "infrastructure-required",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Signed bypass and access policies remain",
  },
  {
    id: "sso-previews",
    name: "SSO Protected Previews",
    status: "infrastructure-required",
    provider: "multivrs",
    metered: true,
    evidence: "Workspace SSO and preview authorization remain",
  },
  {
    id: "static-ips",
    name: "Static IPs",
    status: "infrastructure-required",
    provider: "cloudflare",
    metered: true,
    evidence: "Dedicated egress or Cloudflare network product required",
  },
  {
    id: "secure-compute",
    name: "Secure Compute",
    status: "preview",
    provider: "multivrs+cloudflare",
    metered: true,
    evidence: "Internet-disabled isolated containers exist; private networking remains",
  },
  {
    id: "byoc",
    name: "BYOC",
    status: "infrastructure-required",
    provider: "external",
    metered: true,
    evidence: "Customer cloud control plane and deployment agents required",
  },
  {
    id: "soc2",
    name: "SOC 2 Type 2",
    status: "infrastructure-required",
    provider: "external",
    metered: false,
    evidence: "Independent audit and operating evidence required",
  },
  {
    id: "pci",
    name: "PCI DSS",
    status: "infrastructure-required",
    provider: "external",
    metered: false,
    evidence: "Scoped assessment and attestation required",
  },
  {
    id: "iso27001",
    name: "ISO 27001",
    status: "infrastructure-required",
    provider: "external",
    metered: false,
    evidence: "ISMS certification required",
  },
  {
    id: "dpf",
    name: "EU-U.S. DPF",
    status: "infrastructure-required",
    provider: "external",
    metered: false,
    evidence: "Legal certification required",
  },
  {
    id: "hipaa",
    name: "HIPAA BAA",
    status: "infrastructure-required",
    provider: "external",
    metered: false,
    evidence: "BAAs, controls, and compliance program required",
  },
  {
    id: "tisax",
    name: "TISAX",
    status: "infrastructure-required",
    provider: "external",
    metered: false,
    evidence: "Independent assessment required",
  },
  {
    id: "security-questionnaire",
    name: "Custom Security Questionnaire",
    status: "available",
    provider: "multivrs",
    metered: false,
    evidence: "Enterprise security review is an operational service",
  },
] as const);
